Repository boostcampwm2023/and01-SnapPoint, pull requests merged in 2023-12, with the labels that each got.

#209 Feature(#176): 로그아웃 추가 구현
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivityEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/setting/SettingEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/setting/SettingFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/setting/SettingViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/signin/SignInViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/SignInUtil.kt
  android/app/src/main/res/layout/fragment_setting.xml
  android/app/src/main/res/values/strings.xml
Labels: FEAT, AOS

#212 Release: 로그아웃 API `NoAuth 제거` 릴리즈
  backend/src/api/auth/auth.controller.ts
Labels: FIX, BE, RELEASE

#223 Feature(#220, #219): Redis 구축 및 게시물 별 스냅핀, 파일 캐싱 구현
  backend/package.json
  backend/src/api/api.module.ts
  backend/src/api/auth/auth.module.ts
  backend/src/api/post-api/post-api.controller.spec.ts
  backend/src/api/post-api/post-api.service.spec.ts
  backend/src/api/post-api/post-api.service.ts
  backend/src/app.module.ts
  backend/src/common/mocks/mock.redis.ts
  backend/src/common/redis/redis-cache.module.ts
  backend/src/common/redis/redis-cache.service.spec.ts
  backend/src/common/redis/redis-cache.service.ts
  backend/yarn.lock
Labels: FEAT, BE

#225 Feature(#58, #60, #61): 이미지 144p, 480p, 1080p 처리 및 `Message Ack` 구현
  backend/package.json
  backend/prisma/schema.prisma
  backend/src/api/file-api/dto/file.dto.ts
  backend/src/api/file-api/file-api.controller.ts
  backend/src/api/file-api/file-api.service.spec.ts
  backend/src/api/file-api/file-api.service.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/common/guards/jwt-auth.guard.ts
  backend/src/common/health/health.controller.spec.ts
  backend/src/common/health/health.controller.ts
  backend/src/common/health/health.module.ts
  backend/src/domain/refresh-token/refresh-token.module.ts
  backend/src/main.ts
  backend/yarn.lock
  file/package.json
  file/src/api/file-api/file-api.controller.ts
  file/src/app.module.ts
  file/src/common/health/health.controller.spec.ts
  file/src/common/health/health.controller.ts
  file/src/common/health/health.module.ts
  file/yarn.lock
  media/src/image/image.controller.ts
  media/src/image/image.service.ts
  media/src/main.ts
Labels: FEAT, BE

#224 Fix: 네비게이션 화면 전환 수정
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/auth/signin/SignInFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/auth/signup/SignupFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/auth/signup/SignupViewModel.kt
  android/app/src/main/res/values/strings.xml
Labels: FIX, AOS

#226 Feature(#58): 동영상, 이미지 업로드 구현
  backend/src/api/file-api/file-api.controller.ts
  backend/src/api/file-api/file-api.service.ts
  file/package.json
  file/src/api/file-api/file-api.controller.ts
  file/src/main.ts
  file/src/upload/dtos/part.dto.ts
  file/src/upload/dtos/upload-file-abort.dto.ts
  file/src/upload/dtos/upload-file-end.dto.ts
  file/src/upload/dtos/upload-file-end.response.dto.ts
  file/src/upload/dtos/upload-file-start.response.dto.ts
  file/src/upload/dtos/upload-file-url.dto.ts
  file/src/upload/dtos/uploaded-file.dto.ts
  file/src/upload/storages/bucket.service.ts
  file/src/upload/upload.service.ts
  file/yarn.lock
Labels: FEAT, BE

#232 Feature(#64): 게시글 요약 기능 구현
  backend/prisma/schema.prisma
  backend/src/api/api.module.ts
  backend/src/api/file-api/file-api.service.ts
  backend/src/api/post-api/post-api.controller.ts
  backend/src/api/post-api/post-api.service.ts
  backend/src/api/summarization/summarization.service.ts
  backend/src/api/validation/validation.service.ts
  backend/src/app.module.ts
  backend/src/common/mocks/mock.entity.post.ts
  backend/src/common/prisma/prisma.module.ts
  backend/src/domain/block/block.module.ts
  backend/src/domain/block/block.repository.ts
  backend/src/domain/block/block.service.ts
  backend/src/domain/block/dtos/delete-blocks-by-post.dto.ts
  backend/src/domain/block/dtos/find-blocks-by-area.dto.ts
  backend/src/domain/block/dtos/find-blocks-by-id.dto.ts
  backend/src/domain/block/dtos/find-blocks-by-post.dto.ts
  backend/src/domain/block/dtos/upsert-block.dto.ts
  backend/src/domain/file/dtos/create-file.dto.ts
  backend/src/domain/file/dtos/find-files-by-id.dto.ts
  backend/src/domain/file/dtos/find-files-by-source.dto.ts
  backend/src/domain/file/dtos/process-file.dto.ts
  backend/src/domain/file/file.module.ts
  backend/src/domain/file/file.repository.ts
  backend/src/domain/file/file.service.ts
  backend/src/domain/post/dtos/create-post.dto.ts
  backend/src/domain/post/dtos/post.dto.ts
  backend/src/domain/post/dtos/summary-post.dto.ts
Labels: FEAT, BE

#233 Feature: 게시글 간편 조회 추가, 인증 인가 엔드포인트 수정
  backend/src/api/auth/auth.controller.ts
  backend/src/api/post-api/dtos/read-post.query.dto.ts
  backend/src/api/post-api/post-api.controller.ts
  backend/src/api/post-api/post-api.service.ts
  backend/src/domain/post/dtos/post.dto.ts
Labels: FEAT, BE

#234 Feature(#15, #36): 영상 블록을 포함한 게시글 생성
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/VideoAbortRequest.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/VideoEndRequest.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/VideoUrlRequest.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/VideoEndResponse.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/VideoStartResponse.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/VideoUrlResponse.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/di/RemoteModule.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/auth/signin/SignInViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/PostCreation.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/Constants.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/videoedit/VideoEditActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/videoedit/VideoEditViewModel.kt
  android/app/src/main/res/layout/activity_video_edit.xml
  android/app/src/main/res/layout/item_video_block.xml
Labels: DESIGN, FIX, REFACTOR, AOS

#239 Feat: 게시물 미디어 블록 api 변경사항 적용 및 스냅포인트 썸네일 이미지 적용
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/PostBlock.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/CreatePostResponse.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/GetPostResponse.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MapManager.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/Post.kt
Labels: FEAT, REFACTOR, AOS

#238 FIX(): 썸네일 업로드, 레디스 mget 수정
  backend/src/api/post-api/dtos/write-block-files.dto.ts
  backend/src/common/redis/redis-cache.service.ts
Labels: FIX, BE

#244 Fix: 위도 경도 검사시 ! 대신 undefined인지 검사하는 로직으로 변경
  backend/src/api/validation/validation.service.ts
Labels: FIX, BE

#245 Fix: redis 버그 수정 / 실제 디비에서 가져오는 경우
  backend/src/api/post-api/post-api.service.ts
Labels: FIX, BE

#246 Feature(#61): `ffmpeg`를 사용한 동영상 처리 프로세스 추가
  backend/src/api/file-api/file-api.controller.ts
  backend/src/api/file-api/file-api.service.ts
  backend/src/api/post-api/dtos/file.dto.ts
  backend/src/api/post-api/post-api.service.ts
  backend/src/domain/block/dtos/block.dto.ts
  file/src/api/file-api/file-api.controller.ts
  file/src/upload/upload.service.ts
  media/package-lock.json
  media/package.json
  media/src/app.module.ts
  media/src/image/image.controller.ts
  media/src/image/image.service.ts
  media/src/storage/cloud/bucket.service.ts
  media/src/storage/dtos/delete-file.dto.ts
  media/src/storage/dtos/upload-file.dto.ts
  media/src/storage/dtos/upload-temp-file.dto.ts
  media/src/storage/storage.service.ts
  media/src/video/dtos/metadata.dto.ts
  media/src/video/dtos/process-video.dto.ts
  media/src/video/video-manager.service.ts
  media/src/video/video.controller.spec.ts
  media/src/video/video.controller.ts
  media/src/video/video.module.ts
  media/src/video/video.service.spec.ts
  media/src/video/video.service.ts
Labels: FEAT, BE

#248 Feature(#247): 영상 편집 및 업로드 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/VideoUrlResponse.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/PostCreation.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/CacheFileNameMaker.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/LongExtensions.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/videoedit/ThumbnailView.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/videoedit/TimeLineView.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/videoedit/VideoEditActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/videoedit/VideoEditBindingAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/videoedit/VideoEditEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/videoedit/VideoEditViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostBlockViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostListAdapter.kt
  android/app/src/main/res/drawable/icon_player_pause.xml
  android/app/src/main/res/drawable/icon_player_play.xml
  android/app/src/main/res/layout/activity_video_edit.xml
  android/app/src/main/res/layout/item_video_post.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: FEAT, DESIGN, REFACTOR, AOS

#256 Test: 테스트 코드 수정
  backend/src/api/file-api/file-api.controller.spec.ts
  backend/src/api/file-api/file-api.service.spec.ts
  backend/src/api/post-api/post-api.controller.spec.ts
  backend/src/api/post-api/post-api.service.spec.ts
  backend/src/common/health/health.controller.spec.ts
  file/src/common/health/health.controller.spec.ts
  file/src/upload/upload.service.spec.ts
  media/src/image/image.controller.spec.ts
  media/src/image/image.service.spec.ts
  media/src/storage/storage.service.spec.ts
  media/src/video/video.controller.spec.ts
  media/src/video/video.service.spec.ts
Labels: TEST, BE

#258 Feature: 게시물 정보 반환시 유저 정보도 같이 반환
  backend/src/api/post-api/post-api.controller.spec.ts
  backend/src/api/post-api/post-api.service.spec.ts
  backend/src/api/post-api/post-api.service.ts
  backend/src/domain/post/dtos/post.dto.ts
  backend/src/domain/user/user.service.ts
Labels: FEAT, BE

#257 Feature, Fix: 버그 수정 및 기능 개선
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MapManager.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/around/PostItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/preview/PreviewAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/markerpointselector/MarkerPointSelectorActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/positionselector/PositionSelectorActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/positionselector/PositionSelectorEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/positionselector/PositionSelectorViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/search/AutoCompletionViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/search/SearchViewListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/search/SearchViewUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/BindingAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/Constants.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/SnapPointUtil.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/TimeStampUtil.kt
  android/app/src/main/res/layout/activity_maps_marker.xml
  android/app/src/main/res/layout/fragment_post.xml
  android/app/src/main/res/layout/fragment_preview.xml
  android/app/src/main/res/layout/item_around_post.xml
  android/app/src/main/res/values/strings.xml
Labels: FEAT, FIX, AOS

#259 Feature: 게시글 삭제 기능 구현
  backend/src/api/post-api/post-api.controller.ts
  backend/src/api/post-api/post-api.service.ts
  backend/src/domain/block/block.service.ts
  backend/src/domain/file/file.service.ts
Labels: FEAT, BE

#261 Feature: 기능 추가에 따른 개선
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/SnapPointClusterRenderer.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/clusterpreview/ClusterItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/search/SearchResultViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/search/SearchViewListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/ViewPostViewModel.kt
Labels: FEAT, AOS

#262 Fix: 영상 업로드 관련
  android/app/build.gradle.kts
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
Labels: FIX, REFACTOR, AOS

#264 Refactor: 트랜잭션 처리를 `@Transactional()` 데코레이터 방식으로 개선
  backend/src/api/api.module.ts
  backend/src/api/auth/auth.service.spec.ts
  backend/src/api/file-api/file-api.controller.spec.ts
  backend/src/api/file-api/file-api.service.spec.ts
  backend/src/api/post-api/post-api.controller.spec.ts
  backend/src/api/post-api/post-api.service.spec.ts
  backend/src/api/post-api/post-api.service.ts
  backend/src/api/transformation/transformation.service.spec.ts
  backend/src/api/validation/validation.service.spec.ts
  backend/src/app.module.ts
  backend/src/common/health/health.controller.ts
  backend/src/common/health/health.module.ts
  backend/src/common/prisma/prisma.module.ts
  backend/src/common/prisma/prisma.provider.ts
  backend/src/common/prisma/prisma.service.ts
  backend/src/common/transaction/transaction.decorator.ts
  backend/src/common/transaction/transaction.key.ts
  backend/src/common/transaction/transaction.manager.ts
  backend/src/common/transaction/transaction.module.ts
  backend/src/common/transaction/transaction.storage.ts
  backend/src/common/transaction/tx-prisma.service.ts
  backend/src/domain/block/block.module.ts
  backend/src/domain/block/block.repository.ts
  backend/src/domain/file/file.module.ts
  backend/src/domain/file/file.repository.ts
  backend/src/domain/post/post.module.ts
  backend/src/domain/post/post.service.ts
  backend/src/domain/refresh-token/refresh-token.module.ts
  backend/src/domain/refresh-token/refresh-token.service.spec.ts
  backend/src/domain/refresh-token/refresh-token.service.ts
  backend/src/domain/user/user.module.ts
  backend/src/domain/user/user.service.spec.ts
  backend/src/domain/user/user.service.ts
Labels: REFACTOR, BE
