Repository boostcampwm2023/and01-SnapPoint, pull requests merged in 2023-11, with the labels that each got.

#4 Setting: Nest 프로젝트 초기 설정
  .gitignore
  backend/.eslintrc.js
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.build.json
  backend/tsconfig.json
  backend/yarn.lock
Labels: SETTING, BE

#72 Setting: 프로젝트 기본 설정
  android/.gitignore
  android/app/.gitignore
  android/app/build.gradle.kts
  android/app/proguard-rules.pro
  android/app/src/androidTest/java/com/boostcampwm2023/snappoint/ExampleInstrumentedTest.kt
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/boostcampwm2023/snappoint/SnapPointApp.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/di/RepositoryModule.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseFragment.kt
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/ic_launcher_foreground.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
  android/app/src/main/res/xml/backup_rules.xml
  android/app/src/main/res/xml/data_extraction_rules.xml
  android/app/src/test/java/com/boostcampwm2023/snappoint/ExampleUnitTest.kt
  android/build.gradle.kts
  android/gradle.properties
  android/gradle/libs.versions.toml
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle.kts
Labels: SETTING, AOS

#75 Feature(#33): 게시물 내용을 담는 `UiState` 생성 및 `repository` 생성
  android/app/src/androidTest/java/com/boostcampwm2023/snappoint/MediaRepositoryTest.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/MediaRepository.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/MediaRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/di/RemoteModule.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/di/RepositoryModule.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/CreatePostUiState.kt
Labels: FEAT, AOS

#76 Feature(#9): 게시물 작성 화면 UI 구현
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
  android/app/src/main/res/drawable/icon_arrow_back.xml
  android/app/src/main/res/drawable/icon_check.xml
  android/app/src/main/res/drawable/icon_photo_block.xml
  android/app/src/main/res/drawable/icon_text_block.xml
  android/app/src/main/res/drawable/icon_video_block.xml
  android/app/src/main/res/layout/fragment_create_post.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
  android/gradle/libs.versions.toml
  android/gradle/wrapper/gradle-wrapper.properties
Labels: FEAT, DESIGN, AOS

#73 SETTING(#71): backend `CI` script 작성
  .github/workflows/backend-ci.yml
  backend/.nvmrc
Labels: SETTING, BE

#78 Feature(#77): Prisma 구축 및 `스키마` 작성
  .gitignore
  backend/.gitignore
  backend/package.json
  backend/prisma/schema.prisma
  backend/yarn.lock
Labels: SETTING, BE

#79 Feature(#13): 이미지에서 메타데이터 가져오기
  android/app/build.gradle.kts
  android/app/src/androidTest/java/com/boostcampwm2023/snappoint/MediaRepositoryTest.kt
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/MetadataUtil.kt
  android/gradle/libs.versions.toml
Labels: FEAT, AOS

#80 Conflict: merge conflict 해결
  android/app/build.gradle.kts
  android/app/src/androidTest/java/com/boostcampwm2023/snappoint/MetadataUtilTest.kt
  android/app/src/test/java/com/boostcampwm2023/snappoint/MediaRepositoryTest.kt
  android/gradle/libs.versions.toml
Labels: FIX, SETTING, AOS

#83 Feature(#33): 네트워크 요청 API 작성
  android/app/build.gradle.kts
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/ImageResponse.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/ImageUriResponse.kt
  android/app/src/test/java/com/boostcampwm2023/snappoint/MediaRepositoryTest.kt
  android/gradle/libs.versions.toml
Labels: FEAT, TEST, AOS

#82 Feature(#42): 화면에 지도 표시하기
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/map/MapsMarkerActivity.kt
  android/app/src/main/res/layout/activity_maps_marker.xml
  android/build.gradle.kts
  android/gradle/libs.versions.toml
Labels: DESIGN, SETTING, AOS

#84 Setting(#77) Prisma Client 설정 및 NCP DB와 연결
  backend/.prettierrc
  backend/prisma/schema.prisma
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/prisma.service.ts
Labels: SETTING, BE

#81 Feature(#37): 텍스트 블록 추가 기능
  .gitignore
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/CreatePostUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/PostBlockListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/map/MapsMarkerActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/MetadataUtil.kt
  android/app/src/main/res/drawable/icon_delete.xml
  android/app/src/main/res/drawable/icon_edit.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_create_post.xml
  android/app/src/main/res/layout/item_text_block.xml
  android/app/src/main/res/navigation/nav_graph.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: FEAT, DESIGN, AOS

#85 Feature(#37): `RecyclerView` itemView의 Attach 여부에 따라 TextWatcher 관리
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/PostBlockListAdapter.kt
Labels: FIX, AOS

#86 Setting(#74): Backend CD 구축
  .github/workflows/backend-cd.yml
  backend/.dockerignore
  backend/Dockerfile
  backend/package.json
Labels: SETTING, BE

#87 Feature(#20): 게시물 작성 이벤트 전달 및 입력값 유효성 검사
  android/app/src/androidTest/java/com/boostcampwm2023/snappoint/CreatePostViewModelTest.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/res/layout/fragment_create_post.xml
  android/app/src/main/res/values/strings.xml
Labels: FEAT, AOS

#88 Feature(#15): 마커 움직이기
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/map/MapsMarkerActivity.kt
Labels: FEAT, AOS

#90 Feature(#11): 이미지 블록 추가 기능
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/PostBlockListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/map/MapsMarkerActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/MetadataUtil.kt
  android/app/src/main/res/drawable/icon_arrow_down.xml
  android/app/src/main/res/drawable/icon_arrow_up.xml
  android/app/src/main/res/drawable/icon_cancel.xml
  android/app/src/main/res/drawable/icon_erase_all.xml
  android/app/src/main/res/drawable/icon_location_pin.xml
  android/app/src/main/res/layout/fragment_create_post.xml
  android/app/src/main/res/layout/item_image_block.xml
  android/app/src/main/res/layout/item_text_block.xml
  android/app/src/main/res/values/strings.xml
Labels: FEAT, DESIGN, AOS

#91 Feature(#21): api 전송에 필요한 entity 정의
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/PostBlock.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/CreatePostRequest.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/CreatePostResponse.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepository.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/map/MapsMarkerActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/MetadataUtil.kt
  android/app/src/main/res/layout/item_text_block.xml
Labels: FEAT, STYLE, AOS

#92 Feature(#21): 서버 api 요청 화면 로직
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/featurelist/FeatureListFragment.kt
  android/app/src/main/res/layout/fragment_create_post.xml
  android/app/src/main/res/layout/fragment_feature_list.xml
  android/app/src/main/res/navigation/nav_graph.xml
Labels: FEAT, DESIGN, AOS

#93 Feature(#29): 게시물 블록 삭제 기능
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/res/layout/fragment_create_post.xml
  android/app/src/main/res/layout/item_image_block.xml
  android/app/src/main/res/layout/item_text_block.xml
Labels: FEAT, AOS

#96 Feature(#31): 게시물 블록 위치 변경 기능 구현
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/map/MapsMarkerActivity.kt
  android/app/src/main/res/layout/fragment_create_post.xml
  android/app/src/main/res/layout/item_image_block.xml
  android/app/src/main/res/layout/item_text_block.xml
Labels: FEAT, DESIGN, AOS

#97 Feature(#95): 좌표를 주소로 변환해 가져오기
  android/app/src/androidTest/java/com/boostcampwm2023/snappoint/CreatePostViewModelTest.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/map/MapsMarkerActivity.kt
  android/app/src/main/res/layout/activity_maps_marker.xml
  android/app/src/main/res/layout/fragment_create_post.xml
Labels: FEAT, FIX, AOS

#98 Feature(#26): 게시글 등록 버튼 활성화
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/res/layout/fragment_create_post.xml
  android/app/src/main/res/values/strings.xml
Labels: FEAT, FIX, AOS

#100 Feature(#24): 바텀 시트, 바텀 네비게이션
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/markerpointselector/MarkerPointSelectorActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/popularpost/PopularPostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/setting/SettingFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/subscription/SubscriptionFragment.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/activity_maps_marker.xml
  android/app/src/main/res/layout/fragment_around.xml
  android/app/src/main/res/layout/fragment_popular_post.xml
  android/app/src/main/res/layout/fragment_setting.xml
  android/app/src/main/res/layout/fragment_subscription.xml
  android/app/src/main/res/menu/bottom_navigation_menu.xml
  android/app/src/main/res/navigation/nav_bnv.xml
  android/app/src/main/res/values/strings.xml
Labels: FEAT, DESIGN, AOS

#101 Feature(#24): 바텀시트 높이조절
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/MainActivity.kt
  android/app/src/main/res/drawable/icon_popular_post.xml
  android/app/src/main/res/drawable/icon_setting.xml
  android/app/src/main/res/drawable/icon_subscribe.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/menu/bottom_navigation_menu.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/themes.xml
Labels: FEAT, DESIGN, AOS

#103 Feature(#30): 게시글 목록 확인
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostListAdapter.kt
  android/app/src/main/res/layout/fragment_around.xml
  android/app/src/main/res/layout/item_around_post.xml
  android/app/src/main/res/values/strings.xml
Labels: FEAT, DESIGN, AOS

#106 Feature(#41): 게시글 목록 아이템 확장
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/ExpandButtonToggleAnimation.kt
  android/app/src/main/res/layout/item_around_post.xml
  android/app/src/main/res/values/strings.xml
Labels: FEAT, DESIGN, AOS

#108 Feature(#44): 게시물을 바탕으로 지도에 snappoint 표시
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/Post.kt
  android/app/src/main/res/layout/activity_main.xml
Labels: FEAT, REFACTOR, AOS

#110 Feature(#7) Snap Point 표시
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/SnapPointUtil.kt
Labels: FEAT, DESIGN, REFACTOR, AOS

#109 Feature(#6, #22): 미리보기 화면 상단 바
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivityEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/mainbindingAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_preview.xml
  android/app/src/main/res/menu/preview_app_bar_menu.xml
Labels: FEAT, DESIGN, AOS

#111 Feature(#43): 미리보기 화면 마커/경로
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/res/layout/fragment_around.xml
Labels: FEAT, AOS

#112 Feature(#43): 미리보기 화면으로 이동
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivityEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_around.xml
Labels: FEAT, AOS

#113 Feature(#7): 이미지 SnapPoint 디자인 반영
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/IntExtensions.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/SnapPointUtil.kt
  android/app/src/main/res/drawable/icon_snap_point_container.png
  android/app/src/main/res/drawable/icon_snap_point_focused.png
  android/app/src/main/res/drawable/icon_snap_point_unfocused.png
Labels: FEAT, DESIGN, AOS

#114 Feature(#32): 미리보기 화면에서 하단 네비게이션 이벤트 수정
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/mainbindingAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt
  android/app/src/main/res/navigation/nav_bnv.xml
Labels: FIX, AOS

#117 Feature(#59, #63): 게시글을 블럭 단위로 저장하고, 게시글과 연관 블록 정보를 반환
  backend/package.json
  backend/prisma/schema.prisma
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/block-file/block-file.module.ts
  backend/src/block-file/block-file.service.spec.ts
  backend/src/block-file/block-file.service.ts
  backend/src/block-file/dtos/create-block-files.dto.ts
  backend/src/block/block.module.ts
  backend/src/block/block.service.spec.ts
  backend/src/block/block.service.ts
  backend/src/block/dtos/block.dto.ts
  backend/src/block/dtos/create-block.dto.ts
  backend/src/bucket.service.ts
  backend/src/file/dto/create-file.dto.ts
  backend/src/file/dto/file.dto.ts
  backend/src/file/dto/update-file.dto.ts
  backend/src/file/file.controller.spec.ts
  backend/src/file/file.controller.ts
  backend/src/file/file.module.ts
  backend/src/file/file.service.spec.ts
  backend/src/file/file.service.ts
  backend/src/main.ts
  backend/src/post-api/dtos/create-post-api.dto.ts
  backend/src/post-api/post-api.controller.spec.ts
  backend/src/post-api/post-api.controller.ts
  backend/src/post-api/post-api.module.ts
  backend/src/post-api/post-api.service.spec.ts
  backend/src/post-api/post-api.service.ts
  backend/src/post/dtos/create-post.dto.ts
  backend/src/post/dtos/post.dto.ts
  backend/src/post/post.module.ts
  backend/src/post/post.service.spec.ts
  backend/src/post/post.service.ts
  backend/src/prisma/prisma.module.ts
  backend/src/prisma/prisma.provider.ts
  backend/tsconfig.json
  backend/yarn.lock
Labels: FEAT, BE

#120 [TEST] 블록 도메인 서비스 테스트 코드 추가
  backend/src/block/block.service.spec.ts
Labels: TEST, BE

#121 Test: 미디어 블록 좌표 검사 테스트 추가
  backend/src/block/block.service.spec.ts
Labels: TEST, BE

#122 Refactor: 도메인 테스트 코드 리팩토링
  backend/src/block/block.service.spec.ts
Labels: REFACTOR, BE

#123 Feature(#20): 서버 api 연결
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/PostBlock.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/CreatePostRequest.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/CreatePostResponse.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepository.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/di/RemoteModule.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/markerpointselector/MarkerPointSelectorActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/Post.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewAdapter.kt
  android/app/src/main/res/layout/activity_create_post.xml
  android/app/src/main/res/layout/item_text_block.xml
  android/app/src/main/res/navigation/nav_graph.xml
Labels: FEAT, SETTING, AOS

#125 Refactor: 안드로이드 코드 리팩토링
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemEventListener.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/res/layout/activity_create_post.xml
  android/app/src/main/res/layout/item_image_block.xml
Labels: FIX, REFACTOR, AOS

#124 Feature(#35): 보고있는 이미지와 스냅포인트의 하이라이트 연결
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt
Labels: FEAT, AOS

#116 Feature(#128): 경로가 한 번에 보이도록 카메라 조절
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/Constants.kt
Labels: FEAT, AOS

#126 Feature(#45): 이미지 위의 텍스트가 잘 보이도록 개선
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt
  android/app/src/main/res/layout/fragment_preview.xml
  android/app/src/main/res/layout/item_image_preview.xml
Labels: FIX, AOS

#129 Feature: 구독 화면 내부에 게시물 생성 화면이동 버튼 연결
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/subscription/SubscriptionFragment.kt
  android/app/src/main/res/layout/fragment_subscription.xml
  android/app/src/main/res/values/strings.xml
Labels: PLAN, AOS

#128 Feature(#32): 스냅포인트 클릭 시 미리보기 및 게시글 목록 수정
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt
  android/app/src/main/res/layout/item_around_post.xml
Labels: FEAT, AOS

#130 Feature(#7): 스냅 포인트 이미지 설정
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
Labels: FEAT, FIX, AOS

#131 Feature(): 로그인, 회원가입 기능 구현
  backend/package.json
  backend/prisma/schema.prisma
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/create-auth.dto.ts
  backend/src/auth/dto/login-auth.dto.ts
  backend/src/auth/dto/login.dto.ts
  backend/src/auth/dto/refresh-auth.dto.ts
  backend/src/auth/dto/refresh.dto.ts
  backend/src/auth/guards/jwt-auth.guard.ts
  backend/src/auth/strategies/auth.jwt.strategy.ts
  backend/src/decorator/no-auth.decorator.ts
  backend/src/main.ts
  backend/src/post-api/post-api.controller.ts
  backend/src/post-api/post-api.module.ts
  backend/src/post-api/post-api.service.ts
  backend/src/refresh-token/dto/create-refresh-token.dto.ts
  backend/src/refresh-token/refresh-token.module.ts
  backend/src/refresh-token/refresh-token.service.spec.ts
  backend/src/refresh-token/refresh-token.service.ts
  backend/src/user/dto/create-user.dto.ts
  backend/src/user/dto/update-user.dto.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.spec.ts
  backend/src/user/user.service.ts
  backend/tsconfig.json
  backend/yarn.lock
Labels: FEAT, BE

#153 Feature(#150, #152): 리프레시 토큰, 재발급, 삭제 api 구현
  backend/src/api/auth/auth.controller.ts
  backend/src/api/auth/auth.service.spec.ts
  backend/src/api/auth/auth.service.ts
  backend/src/api/auth/dto/refresh-auth.dto.ts
  backend/src/api/post-api/post-api.controller.ts
  backend/src/common/decorator/cookie.decorator.ts
  backend/src/common/guards/jwt-auth.guard.ts
  backend/src/domain/refresh-token/dto/delete-refresh-token.dto.ts
  backend/src/domain/refresh-token/refresh-token.service.ts
Labels: FEAT, BE

#144 Feature(#133): 로그인 화면 UI
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginFormState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginViewModel.kt
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
Labels: DESIGN, AOS

#159 [DOCS]: 로그아웃 Swagger 설명 수정
  backend/src/api/auth/auth.controller.ts
Labels: SETTING, DOCS, BE

#158 Feature(#51,#52,#53): 게시글 화면 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/Post.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/ViewPostActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/ViewPostEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/ViewPostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostBindingAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostBlockViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostViewModel.kt
  android/app/src/main/res/layout/activity_view_post.xml
  android/app/src/main/res/layout/fragment_around.xml
  android/app/src/main/res/layout/fragment_post.xml
  android/app/src/main/res/layout/item_image_post.xml
  android/app/src/main/res/layout/item_text_post.xml
  android/app/src/main/res/navigation/nav_view_post.xml
  android/app/src/main/res/values/colors.xml
Labels: FEAT, DESIGN, AOS

#160 Feature(#134, #136): 로그인 요청, 실패 메시지
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/LoginRequest.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/LoginRepository.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/LoginRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/di/RemoteModule.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/di/RepositoryModule.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginFormState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: FEAT, AOS

#161 Fix(): 중복 회원가입 예외 처리
  .github/workflows/backend-dev-cd.yml
  backend/src/api/auth/auth.controller.ts
  backend/src/api/auth/auth.service.ts
  backend/src/api/auth/dto/signup.dto.ts
Labels: FIX, BE

#162 Release: 회원가입 중복 예외 처리 수정 및 배포
  .github/workflows/backend-dev-cd.yml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/LoginRequest.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/LoginRepository.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/LoginRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/di/RemoteModule.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/di/RepositoryModule.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostItemViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginFormState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/Post.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/ViewPostActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/ViewPostEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/ViewPostViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostBindingAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostBlockViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostViewModel.kt
  android/app/src/main/res/layout/activity_view_post.xml
  android/app/src/main/res/layout/fragment_around.xml
  android/app/src/main/res/layout/fragment_post.xml
  android/app/src/main/res/layout/item_image_post.xml
  android/app/src/main/res/layout/item_text_post.xml
  android/app/src/main/res/navigation/nav_view_post.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  backend/src/api/auth/auth.controller.ts
  backend/src/api/auth/auth.service.ts
  backend/src/api/auth/dto/signup.dto.ts
  backend/src/api/post-api/post-api.controller.ts
Labels: FIX, BE

#164 setting: android - develop branch merge 자동 배포
  .github/workflows/android-firebase-app-distribution.yml
Labels: SETTING, AOS

#175 Setting: signingConfig 설정 및 action 연결
  .github/workflows/android-firebase-app-distribution.yml
  android/app/build.gradle.kts
  android/app/release/output-metadata.json
Labels: SETTING, AOS

#174 Test: Post API 테스트 코드 이관 및 다른 테스트 모듈 의존성 해결
  backend/src/api/auth/auth.service.spec.ts
  backend/src/api/file-api/file-api.controller.spec.ts
  backend/src/api/post-api/post-api.controller.spec.ts
  backend/src/api/post-api/post-api.service.spec.ts
  backend/src/api/post-api/post-api.service.ts
  backend/src/api/validation/dtos/validate-block.dto.ts
  backend/src/api/validation/dtos/validate-file.dto.ts
  backend/src/api/validation/validation.service.spec.ts
  backend/src/api/validation/validation.service.ts
  backend/src/domain/block/block.service.spec.ts
  backend/src/domain/file/file.service.spec.ts
  backend/src/domain/post/post.service.spec.ts
  backend/src/domain/user/user.service.spec.ts
  backend/tsconfig.json
Labels: TEST, BE

#181 Feature(#34): 주소 검색 및 카메라 이동
  android/app/build.gradle.kts
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivityEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/search/AutoCompletionViewHolder.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/search/SearchViewListAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/search/SearchViewUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/Constants.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/item_search_auto_complete.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: FEAT, AOS

#185 Feature(#40): 현재 위치에서 다시 검색
  android/app/build.gradle.kts
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/res/layout/activity_main.xml
Labels: FEAT, AOS

#179 Feature(#135, #176): 로그인 요청, 로그아웃 요청
  android/app/build.gradle.kts
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/LoginResponse.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/LoginRepository.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/LoginRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/di/RemoteModule.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/setting/SettingFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/setting/SettingViewModel.kt
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/fragment_setting.xml
  android/gradle/libs.versions.toml
Labels: FEAT, AOS

#188 Fix: post-api의 sign-in 임시 처리 제거
  backend/src/api/post-api/post-api.controller.ts
Labels: FIX, BE

#190 Fix: post-api의 sign-in 임시 처리 제거
  backend/src/api/post-api/post-api.controller.ts
Labels: FIX, BE

#192 Style: Post-API 상대 경로를 절대 경로로 수정
  backend/src/api/post-api/post-api.controller.ts
  backend/src/api/post-api/post-api.service.ts
Labels: STYLE, BE

#198 FIX: 엑세스 토큰 만료시 재발급
  backend/src/api/auth/auth.controller.ts
  backend/src/api/auth/auth.module.ts
  backend/src/api/auth/auth.service.spec.ts
  backend/src/api/auth/auth.service.ts
  backend/src/common/guards/jwt-auth.guard.ts
  backend/src/common/strategies/auth.jwt.strategy.ts
  backend/src/domain/refresh-token/refresh-token.service.ts
Labels: FIX, BE

#200 Fix: 회원가입, 로그인시 dto validation 설정
  backend/src/api/auth/auth.controller.ts
  backend/src/api/auth/dto/create-auth.dto.ts
  backend/src/app.module.ts
Labels: FIX, BE

#203 FIX: MainUiState가 업데이트 될 때 불필요한 UI도 업데이트 되는 문제 수정
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MarkerUiState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/mainbindingAdapter.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/SnapPointUtil.kt
Labels: FIX, REFACTOR, AOS

#202 Feature(#194, #195): splash 화면에서 자동 로그인 시도
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/SignInRequest.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/SignInResponse.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/LoginRepository.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/SignInRepository.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/SignInRepositoryImpl.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/di/RepositoryModule.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/setting/SettingViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/signin/SignInEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/signin/SignInFormState.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/signin/SignInFragment.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/signin/SignInViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/signin/SigninEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/signup/SignupViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/splash/SplashEvent.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/SignInUtil.kt
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/layout/fragment_signin.xml
  android/app/src/main/res/navigation/nav_auth.xml
  android/app/src/main/res/values/strings.xml
Labels: FEAT, AOS

#204 Feature: andorid ci ktlint 적용
  .github/workflows/android-ci.yml
Labels: FEAT, AOS
